version: "3.3"

services:

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage:z

  ollama:
    container_name: ollama
    image: ollama/ollama
#    command:
#      - bash -c "ollama run llama3.1:8b"
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama


volumes:
  ollama:
  qdrant_storage:
